@url = http://localhost:3000/api/orders

# URL del servicio de Kubernetes
@url = http://localhost:30940/api/orders

# URL del servicio de Kubernetes desde el Ingress
@url = http://34.8.174.133/api/orders

### Crear un nuevo pedido
POST {{url}}
Content-Type: application/json

{
  "items": [
    {
      "productId": 3,
      "quantity": 2,
      "price": 150
    },
    {
      "productId": 5,
      "quantity": 1,
      "price": 50
    }    
  ]
}

### Obtener todos los pedidos
GET {{url}}?page=1&limit=10&status=PENDING

### Obtener todos los pedidos por status
GET {{url}}/CANCELLED?page=1&limit=10


### Obtener un pedido por ID
GET {{url}}/id/03c438a6-1f02-4c9a-a736-92f479d7d697

### Cambiar el estado de un pedido por ID
PATCH {{url}}/fb41cf12-b788-4515-8f0f-e43ced10a4a4
Content-Type: application/json

{
  "status": "DELIVERED"
}
