services:

  nats-server:
    image: nats:latest
    
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_PROJECT_ID}/${DOCKER_REGISTRY_PROJECT}/client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_PROJECT_ID}/${DOCKER_REGISTRY_PROJECT}/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_PROJECT_ID}/${DOCKER_REGISTRY_PROJECT}/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - PRODUCTS_DATABASE_URL=${PRODUCTS_DATABASE_URL}
  
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_PROJECT_ID}/${DOCKER_REGISTRY_PROJECT}/orders-ms
    environment:
      - PORT=3000
      - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_PROJECT_ID}/${DOCKER_REGISTRY_PROJECT}/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      