apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: europe-southwest1-docker.pkg.dev/nestjs-microservicios-456909/nestjs-microservicios/payments-ms:latest
        name: payments-ms
        resources: {}
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats-server"
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:3000/payments/success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:3000/payments/cancel"
          - name: STRIPE_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-ms-secrets
                key: STRIPE_SECRET
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-ms-secrets
                key: STRIPE_ENDPOINT_SECRET
status: {}
