apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
