apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-ms
  name: payment-ms
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: payment-ms
  type: NodePort
status:
  loadBalancer: {}
