apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nats-server
  name: nats-server
spec:
  ports:
  - name: "4222"
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats-server
  type: ClusterIP
status:
  loadBalancer: {}
