@url = http://localhost:3000/api/auth

# URL del microservicio de auth-ms
@url = http://localhost:30940/api/auth

### Login
# @name login
POST {{url}}/login
Content-Type: application/json

{
  "email": "usuario@gmail.com",
  "password": "1234567!02JSJSJSssswd"
}

### Install httpbin and run using docker with "docker run -p 80:80 kennethreitz/httpbin"
GET http://0.0.0.0:80/anything
Content-Type: application/json
X-Full-Response: {{login.response.body.*}}

### Crear un nuevo usuario
POST {{url}}/register
Content-Type: application/json

{
  "name": "Usuario XXX",
  "email": "usuario@gmail.com",
  "password": "1234567!02JSJSJSssswd"
}

### Verificar token
GET {{url}}/verify
Authorization: Bearer {{login.response.body.token}}
